### ISSUE TITLE
Too few arguments to function Meema\MediaConverter\Converters\MediaConvert::createJob(), 0 passed in

### ISSUE THREAD

**Issue by injektion** [meemalabs/laravel-media-converter#21]
Following the example for simple job:

```
use Meema\MediaConverter\Facades\MediaConvert;
use Meema\MediaConverter\Jobs\CreateVideoConversion;

# simple usage
MediaConvert::path('video.mkv') // the s3 path to the file inside the bucket defined in your config (filesystems.disks.s3.bucket)
    ->optimizeForWeb() // will generate an optimized MP4 for you
    ->withThumbnails(int $framerateNumerator, int $framerateDenominator, int $maxCaptures, $width = null, $nameModifier = null, $imageQuality = 80) // will generate thumbnails from the video for you, e.g. poster images
    ->saveTo('my-optimized-video.mp4'); // output file name
    ->createJob();
```

I dropped the extra ; after the saveTo but createJob() is generating this error:

`Too few arguments to function Meema\MediaConverter\Converters\MediaConvert::createJob(), 0 passed in`

Anything missing from the example, or anything you can suggest to fix?

Thanks!

**Comment by chrisbbreuer** [comment]
Hi @injektion,

Thanks for commenting on this issue, and, yes, we would love to help out. It appears like something is not working correctly and we will have this looked into ASAP and ping you with updates. 🙂

cc @glennmichael123, could you please take a look?

Thanks!
Chris

**Comment by glennmichael123** [comment]
Hi @injektion issue fixed in this [PR](https://github.com/meemalabs/laravel-media-converter/pull/22)

@Chris1904 Kindly check the code and the tests then merge it it's all good to go.

Thanks!

**Comment by chrisbbreuer** [comment]
Thanks, Glenn!

I just released a new version that includes this bug fix. 

Ping me if there is anything else I/we can help clarify. 👍🏼
