### ISSUE TITLE
Undefined array key "model_id"

### ISSUE THREAD

**Issue by wiaamLB** [meemalabs/laravel-media-converter#26]
laravel-media-converter/src/Models/MediaConversion.php(55)

![image](https://user-images.githubusercontent.com/19538693/152232398-b635c857-ce97-48a9-9980-d84296049da9.png)

**Comment by chrisbbreuer** [comment]
Hi there, interesting. I am not quite sure what that could be. Could you please provide some more context? Maybe point me to a minimal reproduction repo? 🙏🏼

**Comment by chrisbbreuer** [comment]
I will reopen this if there is minimal reproduction for us :-)
